// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace mueblesGeanella.API.Migrations
{
    [DbContext(typeof(mueblesGeanellaAPIContext))]
    partial class mueblesGeanellaAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("mueblesGeanella.Modelos.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cedula");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("direccion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("telefono");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.HasKey("IdCliente");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("mueblesGeanella.Modelos.DetalleFactura", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<int>("IdFactura")
                        .HasColumnType("integer")
                        .HasColumnName("id_factura");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio");

                    b.Property<int?>("facturaIdFactura")
                        .HasColumnType("integer");

                    b.Property<int?>("productoIdProducto")
                        .HasColumnType("integer");

                    b.HasKey("IdDetalle");

                    b.HasIndex("facturaIdFactura");

                    b.HasIndex("productoIdProducto");

                    b.ToTable("detalle_factura");
                });

            modelBuilder.Entity("mueblesGeanella.Modelos.Fabricante", b =>
                {
                    b.Property<int>("IdFabricante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_fabricante");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFabricante"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Servicio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("servicio");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("telefono");

                    b.HasKey("IdFabricante");

                    b.ToTable("fabricantes");
                });

            modelBuilder.Entity("mueblesGeanella.Modelos.Factura", b =>
                {
                    b.Property<int>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_factura");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFactura"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("monto_total");

                    b.Property<int?>("clienteIdCliente")
                        .HasColumnType("integer");

                    b.HasKey("IdFactura");

                    b.HasIndex("clienteIdCliente");

                    b.ToTable("facturas");
                });

            modelBuilder.Entity("mueblesGeanella.Modelos.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProducto"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int>("IdFabricante")
                        .HasColumnType("integer")
                        .HasColumnName("id_fabricante");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<int>("Stock")
                        .HasColumnType("integer")
                        .HasColumnName("stock");

                    b.HasKey("IdProducto");

                    b.HasIndex("IdFabricante");

                    b.ToTable("productos");
                });

            modelBuilder.Entity("mueblesGeanella.Modelos.DetalleFactura", b =>
                {
                    b.HasOne("mueblesGeanella.Modelos.Factura", "factura")
                        .WithMany()
                        .HasForeignKey("facturaIdFactura");

                    b.HasOne("mueblesGeanella.Modelos.Producto", "producto")
                        .WithMany()
                        .HasForeignKey("productoIdProducto");

                    b.Navigation("factura");

                    b.Navigation("producto");
                });

            modelBuilder.Entity("mueblesGeanella.Modelos.Factura", b =>
                {
                    b.HasOne("mueblesGeanella.Modelos.Cliente", "cliente")
                        .WithMany()
                        .HasForeignKey("clienteIdCliente");

                    b.Navigation("cliente");
                });

            modelBuilder.Entity("mueblesGeanella.Modelos.Producto", b =>
                {
                    b.HasOne("mueblesGeanella.Modelos.Fabricante", "fabricante")
                        .WithMany()
                        .HasForeignKey("IdFabricante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("fabricante");
                });
#pragma warning restore 612, 618
        }
    }
}
